[package]
name = "amtrak-api"
version = "0.1.0"
edition = "2021"
description = "Amtrak Async Rust API Client"
keywords = ["amtrak", "api", "public-transit", "train"]
readme = "README.md"
repository = "https://github.com/StefanBossbaly/amtrak-api/"
authors = ["Stefan Bossbaly <sbossb@gmail.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.22", features = ["json", "rustls-tls"] }
serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
mockito = "1.2.0"
tokio = { version = "1.35.0", features = ["full"] }

[[example]]
name = "filter_stations"
crate-type = ["bin"]

[[example]]
name = "filter_trains"
crate-type = ["bin"]

[[example]]
name = "single_station"
crate-type = ["bin"]

[[example]]
name = "single_train"
crate-type = ["bin"]
